language: node_js
node_js:
- '0.12'
sudo: false
before_install:
- pip install --user awscli && export PATH=$PATH:~/.local/bin/
script:
- ./bin/build
- aws s3 cp --acl=public-read build/streambot.zip s3://mapbox-us-east-1/release/streambot/${TRAVIS_COMMIT}.zip
- aws s3 cp --acl=public-read build/streambot.zip s3://mapbox-us-west-2/release/streambot/${TRAVIS_COMMIT}.zip
- aws s3 cp --acl=public-read build/streambot.zip s3://mapbox-eu-west-1/release/streambot/${TRAVIS_COMMIT}.zip
- aws s3 cp --acl=public-read build/streambot.zip s3://mapbox-ap-northeast-1/release/streambot/${TRAVIS_COMMIT}.zip
- if git describe --tags --exact-match 2> /dev/null; then aws s3 cp --acl=public-read build/streambot.zip s3://mapbox-us-east-1/release/streambot/$(git describe --tags --exact-match).zip; fi
- if git describe --tags --exact-match 2> /dev/null; then aws s3 cp --acl=public-read build/streambot.zip s3://mapbox-us-west-2/release/streambot/$(git describe --tags --exact-match).zip; fi
- if git describe --tags --exact-match 2> /dev/null; then aws s3 cp --acl=public-read build/streambot.zip s3://mapbox-eu-west-1/release/streambot/$(git describe --tags --exact-match).zip; fi
- if git describe --tags --exact-match 2> /dev/null; then aws s3 cp --acl=public-read build/streambot.zip s3://mapbox-ap-northeast-1/release/streambot/$(git describe --tags --exact-match).zip; fi
- ./bin/bundle ./streambot-example
- aws s3 cp --acl=public-read streambot-example/build/bundle.zip s3://mapbox-us-east-1/release/streambot/${TRAVIS_COMMIT}-example.zip
- aws s3 cp --acl=public-read streambot-example/build/bundle.zip s3://mapbox-us-west-2/release/streambot/${TRAVIS_COMMIT}-example.zip
- aws s3 cp --acl=public-read streambot-example/build/bundle.zip s3://mapbox-eu-west-1/release/streambot/${TRAVIS_COMMIT}-example.zip
- aws s3 cp --acl=public-read streambot-example/build/bundle.zip s3://mapbox-ap-northeast-1/release/streambot/${TRAVIS_COMMIT}-example.zip
- if git describe --tags --exact-match 2> /dev/null; then aws s3 cp --acl=public-read streambot-example/build/bundle.zip s3://mapbox-us-east-1/release/streambot/$(git describe --tags --exact-match)-example.zip; fi
- if git describe --tags --exact-match 2> /dev/null; then aws s3 cp --acl=public-read streambot-example/build/bundle.zip s3://mapbox-us-west-2/release/streambot/$(git describe --tags --exact-match)-example.zip; fi
- if git describe --tags --exact-match 2> /dev/null; then aws s3 cp --acl=public-read streambot-example/build/bundle.zip s3://mapbox-eu-west-1/release/streambot/$(git describe --tags --exact-match)-example.zip; fi
- if git describe --tags --exact-match 2> /dev/null; then aws s3 cp --acl=public-read streambot-example/build/bundle.zip s3://mapbox-ap-northeast-1/release/streambot/$(git describe --tags --exact-match)-example.zip; fi
- npm test
env:
  global:
  - secure: TZpt40WI5Y24ZoBb85x52GBLh719YXUTTQ9tfBLcKrPlh8QXPGUuwPVBOyTX0XOi5fWtADpAZ59zgDlrLiu1Eus39nidbxano9NdzUaYjvV+8PqfVqNgNjpQZXTIKfFERQVE3ILFR82TaSlsFE8GOleZdVafXzl1eFzinQZNiO0=
  - secure: WoGKafmLKLpta+v04w8HxN2UApGzbMaLRrLny4O4q73H77f81PztUSEdyYOtXJCf2XnuNFVkGdthJpVPeZRH3+U80PmhHlUKs/LFJQImgZKC3EF6NvmWrxLpYNoisgoJTujeCXpbjMRwc2NYtn4npMI3bAGf2mJm3UkTaJzEVhM=
